In [4]:
import pandas as pd

# Load your data
df = pd.read_csv(r'D:\Supply_chain_project\data\raw\table.csv')

# Display shape and preview
print(f"Shape: {df.shape}")
df.head()

Shape: (81837, 17)

C:\Users\Devdip  Mallick\AppData\Local\Temp\ipykernel_9364\3013119910.py:4: DtypeWarning: Columns (10,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'D:\Supply_chain_project\data\raw\table.csv')

,date,product_id,sku,category,brand,price,lifecycle_stage,sales_quantity,sales_revenue,promo_flag,promotion_type,discount_percentage,channel,temperature,weather_condition,social_media_mentions,competitor_analysis_score
0,2021-01-01,Hom-Bed-1141,SKU-1141,Home,Bed Bath & Beyond,334.71,Decline,39,13053.69,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-01,Ice-Haa-1057,SKU-1057,Ice Cream,Haagen-Dazs,498.10,Decline,14,6973.40,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-01,Toy-Has-1161,SKU-1161,Toys,Hasbro,281.91,Growth,35,9866.85,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-01,Ice-Haa-1053,SKU-1053,Ice Cream,Haagen-Dazs,313.70,New,46,14430.20,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-01,Boo-Pen-1227,SKU-1227,Books,Penguin,249.20,Growth,9,2242.80,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Show column names with index
for i, col in enumerate(df.columns):
    print(f"{i}: {col}")

0: date
1: product_id
2: sku
3: category
4: brand
5: price
6: lifecycle_stage
7: sales_quantity
8: sales_revenue
9: promo_flag
10: promotion_type
11: discount_percentage
12: channel
13: temperature
14: weather_condition
15: social_media_mentions
16: competitor_analysis_score

In [6]:
import pandas as pd

df = pd.read_csv(
    r'D:\Supply_chain_project\data\raw\table.csv',
    dtype={
        'promotion_type': str,
        'channel': str
    }
)

In [9]:
# See how many missing values are in each column
missing = df.isnull().sum()
missing_percentage = (missing / len(df)) * 100
missing_df = pd.DataFrame({'Missing Values': missing, 'Percentage (%)': missing_percentage})
missing_df[missing_df['Missing Values'] > 0].sort_values(by='Percentage (%)', ascending=False)

                           Missing Values  Percentage (%)
social_media_mentions               81785       99.936459
weather_condition                   81785       99.936459
temperature                         81785       99.936459
competitor_analysis_score           81785       99.936459
discount_percentage                 81384       99.446461
channel                             79998       97.752850
promotion_type                      79998       97.752850

In [10]:
# Drop columns with more than 90% missing values
df.drop(columns=['social_media_mentions', 'weather_condition', 'temperature', 'competitor_analysis_score'], inplace=True)

In [14]:
for i, col in enumerate(df.columns):
    print(f"{i}: {col}")

0: date
1: product_id
2: sku
3: category
4: brand
5: price
6: lifecycle_stage
7: sales_quantity
8: sales_revenue
9: promo_flag
10: promotion_type
11: discount_percentage
12: channel

In [12]:
# Fill missing values in categorical columns with the mode (no inplace=True)
df['channel'] = df['channel'].fillna(df['channel'].mode()[0])
df['promotion_type'] = df['promotion_type'].fillna(df['promotion_type'].mode()[0])

# Fill missing values in numerical columns with the mean
df['discount_percentage'] = df['discount_percentage'].fillna(df['discount_percentage'].mean())

In [13]:
# Check missing values after filling
missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100
print(f"Missing Values after cleaning:\n{missing_values}")
print(f"Missing Values Percentage:\n{missing_percentage}")

Missing Values after cleaning:
date                   0
product_id             0
sku                    0
category               0
brand                  0
price                  0
lifecycle_stage        0
sales_quantity         0
sales_revenue          0
promo_flag             0
promotion_type         0
discount_percentage    0
channel                0
dtype: int64
Missing Values Percentage:
date                   0.0
product_id             0.0
sku                    0.0
category               0.0
brand                  0.0
price                  0.0
lifecycle_stage        0.0
sales_quantity         0.0
sales_revenue          0.0
promo_flag             0.0
promotion_type         0.0
discount_percentage    0.0
channel                0.0
dtype: float64